# Generated by Django 5.2.8 on 2025-11-24 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainer',
            name='cover_url',
            field=models.URLField(blank=True, null=True, verbose_name='Фото'),
        ),
    ]
